name: Build and push docker image.

on:
  push:
    branches: [ main ]

# Permissions to request the OIDC JWT token
permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4 

    # The OIDC Role ARN
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::133850321524:role/OIDC-frontend
          aws-region: us-east-1 # <-- ECR registry region

    # Login to ECR
    #=============
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Build, tag, and push using ECR registry variables
    - name: Docker build and push
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: movie-frontend
        IMAGE_TAG: v${{ github.run_number }}
      run: | 
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG